name: ebooks_reader
description: "Epub reader"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  asuka: ^2.2.0
  device_info_plus: ^9.1.1
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  mobx: ^2.2.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  sqflite: ^2.3.0
  synchronized: ^3.1.0
  vocsy_epub_viewer: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
